import unreal


SOURCE_MESH = "/Game/Characters/Mannequins/Meshes/SKM_Manny_Simple"
TARGET_MESH = "/Game/MetaHumans/Human2/Body/SKM_Human2_BodyMesh"
RETARGETER = "/Game/MetaHumans/Human2/Retarget/RTG_AutoGenerated"
OUTPUT_FOLDER = "/Game/MetaHumans/Human2/Animations/Actions"
ANIMATIONS = (
    (
        "/Game/Characters/Mannequins/Anims/Pistol/MM_Pistol_Equip",
        "Human2_MM_Pistol_Equip",
    ),
    (
        "/Game/Characters/Mannequins/Anims/Pistol/MF_Pistol_Idle_ADS",
        "Human2_MF_Pistol_Idle_ADS",
    ),
    (
        "/Game/Characters/Mannequins/Anims/Rifle/MM_Rifle_Equip",
        "Human2_MM_Rifle_Equip",
    ),
    (
        "/Game/Characters/Mannequins/Anims/Rifle/MF_Rifle_Idle_ADS",
        "Human2_MF_Rifle_Idle_ADS",
    ),
    (
        "/Game/Characters/Mannequins/Anims/Unarmed/Attack/MM_ChargedAttack",
        "Human2_MM_ChargedAttack",
    ),
)


def require_asset(path):
    asset = unreal.load_asset(path)
    if asset is None:
        raise RuntimeError(f"Required asset could not be loaded: {path}")
    return asset


def asset_data(path):
    data = unreal.EditorAssetLibrary.find_asset_data(path)
    if not data.is_valid():
        raise RuntimeError(f"Asset data could not be found: {path}")
    return data


def verify_animation(animation, target_mesh):
    animation_skeleton = animation.get_editor_property("skeleton")
    target_skeleton = target_mesh.get_editor_property("skeleton")
    if animation_skeleton != target_skeleton:
        raise RuntimeError(
            "Retargeted animation skeleton does not match Human2: "
            f"animation={animation_skeleton} target={target_skeleton}"
        )
    unreal.log(
        "NATURALNPC_ACTION_ANIM_VERIFY "
        f"asset={animation.get_path_name()} "
        f"skeleton={animation_skeleton.get_path_name()} "
        f"length={animation.get_play_length():.3f}"
    )


source_mesh = require_asset(SOURCE_MESH)
target_mesh = require_asset(TARGET_MESH)
retargeter = require_asset(RETARGETER)

for source_path, output_name in ANIMATIONS:
    source_animation = require_asset(source_path)
    output_path = f"{OUTPUT_FOLDER}/{output_name}"
    existing = unreal.load_asset(output_path)
    if existing is not None:
        verify_animation(existing, target_mesh)
        unreal.log(
            "NATURALNPC_ACTION_ANIM existing_asset_reused=true "
            f"asset={output_path}"
        )
        continue

    unreal.EditorAssetLibrary.make_directory(OUTPUT_FOLDER)
    results = unreal.IKRetargetBatchOperation.duplicate_and_retarget(
        [asset_data(source_path)],
        source_mesh,
        target_mesh,
        retargeter,
        "",
        "",
        "Human2_",
        "",
        False,
        True,
    )
    if not results:
        raise RuntimeError("IK retargeting did not produce an animation asset")

    generated = results[0].get_asset()
    generated_path = generated.get_path_name().split(".")[0]
    if generated_path != output_path:
        if not unreal.EditorAssetLibrary.rename_asset(
            generated_path,
            output_path,
        ):
            raise RuntimeError(
                f"Could not move {generated_path} to {output_path}"
            )

    animation = require_asset(output_path)
    unreal.EditorAssetLibrary.save_loaded_asset(animation, False)
    verify_animation(animation, target_mesh)
    unreal.log(
        "NATURALNPC_ACTION_ANIM created=true "
        f"source={source_animation.get_path_name()}"
    )

unreal.log("NATURALNPC_ACTION_ANIM COMPLETE")
