import unreal


PREFIX = "NATURALNPC_SIT_RETARGET"
SOURCE_MESH_PATH = (
    "/Game/Characters/UEFN_Mannequin/Meshes/SKM_UEFN_Mannequin"
)
SOURCE_RIG_PATH = (
    "/Game/Characters/UEFN_Mannequin/Rigs/IK_UEFN_Mannequin"
)
TARGET_MESH_PATH = "/Game/MetaHumans/Human2/Body/SKM_Human2_BodyMesh"
BASE_RETARGETER_PATH = "/Game/MetaHumans/Human2/Retarget/RTG_AutoGenerated"
RETARGETER_PATH = "/Game/MetaHumans/Human2/Retarget/RTG_UEFN_Human2"
OUTPUT_FOLDER = "/Game/MetaHumans/Human2/Animations/Actions"
ANIMATIONS = (
    (
        "/Game/Characters/UEFN_Mannequin/Animations/Interactions/Bench/"
        "M_interaction_bench_into_F_Lfoot",
        f"{OUTPUT_FOLDER}/Human2_SitDown",
    ),
    (
        "/Game/Characters/UEFN_Mannequin/Animations/Interactions/Bench/"
        "M_interaction_bench_idle_loop",
        f"{OUTPUT_FOLDER}/Human2_SitIdle",
    ),
    (
        "/Game/Characters/UEFN_Mannequin/Animations/Interactions/Bench/"
        "M_interaction_bench_out_to_stand",
        f"{OUTPUT_FOLDER}/Human2_StandUp",
    ),
)


def log(message):
    unreal.log(f"{PREFIX} {message}")


def require_asset(path):
    asset = unreal.load_asset(path)
    if asset is None:
        raise RuntimeError(f"Required asset is missing: {path}")
    return asset


def asset_data(path):
    data = unreal.EditorAssetLibrary.find_asset_data(path)
    if not data.is_valid():
        raise RuntimeError(f"Asset data is missing: {path}")
    return data


source_mesh = require_asset(SOURCE_MESH_PATH)
source_rig = require_asset(SOURCE_RIG_PATH)
target_mesh = require_asset(TARGET_MESH_PATH)

retargeter = unreal.load_asset(RETARGETER_PATH)
if retargeter is None:
    retargeter = unreal.EditorAssetLibrary.duplicate_asset(
        BASE_RETARGETER_PATH,
        RETARGETER_PATH,
    )
if retargeter is None:
    raise RuntimeError("Could not create the UEFN to Human2 retargeter")

retarget_controller = unreal.IKRetargeterController.get_controller(retargeter)
retarget_controller.set_ik_rig(
    unreal.RetargetSourceOrTarget.SOURCE,
    source_rig,
)
retarget_controller.auto_map_chains(
    unreal.AutoMapChainType.EXACT,
    True,
)
retarget_controller.auto_align_all_bones(
    unreal.RetargetSourceOrTarget.SOURCE,
    unreal.RetargetAutoAlignMethod.CHAIN_TO_CHAIN,
)
unreal.EditorAssetLibrary.save_loaded_asset(retargeter, False)
log(
    f"retargeter={retargeter.get_path_name()} "
    f"source={retarget_controller.get_ik_rig(unreal.RetargetSourceOrTarget.SOURCE)} "
    f"target={retarget_controller.get_ik_rig(unreal.RetargetSourceOrTarget.TARGET)}"
)

missing_sources = []
missing_outputs = []
for source_path, output_path in ANIMATIONS:
    require_asset(source_path)
    if unreal.load_asset(output_path) is None:
        missing_sources.append(asset_data(source_path))
        missing_outputs.append(output_path)

if missing_sources:
    results = unreal.IKRetargetBatchOperation.duplicate_and_retarget(
        missing_sources,
        source_mesh,
        target_mesh,
        retargeter,
        "",
        "",
        "Human2_",
        "",
        False,
        True,
    )
    if len(results) != len(missing_outputs):
        raise RuntimeError(
            f"Expected {len(missing_outputs)} animations, found {results}"
        )

    for result, output_path in zip(results, missing_outputs):
        generated = result.get_asset()
        generated_path = generated.get_path_name().split(".")[0]
        if generated_path != output_path:
            if not unreal.EditorAssetLibrary.rename_asset(
                generated_path,
                output_path,
            ):
                raise RuntimeError(
                    f"Could not move {generated_path} to {output_path}"
                )

target_skeleton = target_mesh.get_editor_property("skeleton")
for _, output_path in ANIMATIONS:
    animation = require_asset(output_path)
    if animation.get_editor_property("skeleton") != target_skeleton:
        raise RuntimeError(f"Wrong target skeleton: {output_path}")
    animation.set_editor_property("enable_root_motion", False)
    animation.set_editor_property("force_root_lock", False)
    unreal.EditorAssetLibrary.save_loaded_asset(animation, False)
    log(
        f"animation={animation.get_path_name()} "
        f"length={animation.get_play_length():.3f} "
        f"frames={animation.data_model_interface.get_number_of_frames()} "
        "root_motion=false force_root_lock=false"
    )

log("COMPLETE animations=3")
