import unreal


PREFIX = "NATURALNPC_DAILY_PICKUP"
SOURCE_ROOT = (
    "/Game/DailyAnimation/motifect_daily_life_complete_v1_0_fbx/"
    "Import"
)
GENERATED_FOLDER = "/Game/ImportedAnimations/DailyPickup"
BASE_RETARGETER_PATH = "/Game/MetaHumans/Human2/Retarget/RTG_AutoGenerated"
TARGET_MESH_PATH = "/Game/MetaHumans/Human2/Body/SKM_Human2_BodyMesh"
OUTPUT_FOLDER = "/Game/MetaHumans/Human2/Animations/Actions"
VARIANTS = (
    {
        "name": "ground",
        "mesh": (
            f"{SOURCE_ROOT}/Pickup_object_floor/pick_up_object_floor"
        ),
        "animation": (
            f"{SOURCE_ROOT}/Pickup_object_floor/pick_up_object_floor_Anim"
        ),
        "rig": f"{GENERATED_FOLDER}/IK_DailyPickup_Floor",
        "retargeter": (
            f"{GENERATED_FOLDER}/RTG_DailyPickupFloor_Human2"
        ),
        "output": f"{OUTPUT_FOLDER}/Human2_Pickup_Floor",
    },
    {
        "name": "table",
        "mesh": (
            f"{SOURCE_ROOT}/Pickup_object_table/pick_up_object_table"
        ),
        "animation": (
            f"{SOURCE_ROOT}/Pickup_object_table/pick_up_object_table_Anim"
        ),
        "rig": f"{GENERATED_FOLDER}/IK_DailyPickup_Table",
        "retargeter": (
            f"{GENERATED_FOLDER}/RTG_DailyPickupTable_Human2"
        ),
        "output": f"{OUTPUT_FOLDER}/Human2_Pickup_Table",
    },
)


def log(message):
    unreal.log(f"{PREFIX} {message}")


def require_asset(path):
    asset = unreal.load_asset(path)
    if asset is None:
        raise RuntimeError(f"Required asset is missing: {path}")
    return asset


def asset_data(asset):
    path = asset.get_path_name().split(".")[0]
    data = unreal.EditorAssetLibrary.find_asset_data(path)
    if not data.is_valid():
        raise RuntimeError(f"Asset data is missing: {path}")
    return data


def create_source_rig(asset_tools, rig_path, source_mesh):
    rig = unreal.load_asset(rig_path)
    if rig is None:
        rig_name = rig_path.rsplit("/", 1)[-1]
        rig = asset_tools.create_asset(
            rig_name,
            GENERATED_FOLDER,
            unreal.IKRigDefinition,
            unreal.IKRigDefinitionFactory(),
        )
    if rig is None:
        raise RuntimeError(f"Could not create source IK Rig: {rig_path}")

    controller = unreal.IKRigController.get_controller(rig)
    if not controller.set_skeletal_mesh(source_mesh):
        raise RuntimeError(f"Could not assign source mesh to {rig_path}")
    if not controller.get_retarget_chains():
        if not controller.apply_auto_generated_retarget_definition():
            raise RuntimeError(
                f"UE could not auto-generate retarget chains for {rig_path}"
            )
    if not controller.set_retarget_chain_start_bone("Spine", "Spine1"):
        raise RuntimeError(f"Could not set Spine start bone for {rig_path}")
    if not controller.set_retarget_chain_end_bone("Spine", "Chest"):
        raise RuntimeError(f"Could not include Chest in Spine for {rig_path}")
    chain_names = {
        str(chain.chain_name) for chain in controller.get_retarget_chains()
    }
    if "Neck" not in chain_names:
        neck_chain = controller.add_retarget_chain(
            "Neck",
            "Neck1",
            "Neck2",
            "",
        )
        if str(neck_chain) != "Neck":
            raise RuntimeError(f"Could not create Neck chain for {rig_path}")
    else:
        if not controller.set_retarget_chain_start_bone("Neck", "Neck1"):
            raise RuntimeError(f"Could not set Neck start bone for {rig_path}")
        if not controller.set_retarget_chain_end_bone("Neck", "Neck2"):
            raise RuntimeError(f"Could not set Neck end bone for {rig_path}")
    if not controller.get_retarget_root():
        raise RuntimeError(f"Source IK Rig has no retarget root: {rig_path}")
    unreal.EditorAssetLibrary.save_loaded_asset(rig, False)
    log(
        f"SOURCE_RIG path={rig_path} "
        f"root={controller.get_retarget_root()} "
        f"chains={len(controller.get_retarget_chains())} "
        f"spine={controller.get_retarget_chain_start_bone('Spine')}-"
        f"{controller.get_retarget_chain_end_bone('Spine')} "
        f"neck={controller.get_retarget_chain_start_bone('Neck')}-"
        f"{controller.get_retarget_chain_end_bone('Neck')}"
    )
    return rig


def create_retargeter(
    retargeter_path,
    source_rig,
    source_mesh,
    target_mesh,
):
    retargeter = unreal.load_asset(retargeter_path)
    if retargeter is None:
        retargeter = unreal.EditorAssetLibrary.duplicate_asset(
            BASE_RETARGETER_PATH,
            retargeter_path,
        )
    if retargeter is None:
        raise RuntimeError(f"Could not create retargeter: {retargeter_path}")

    controller = unreal.IKRetargeterController.get_controller(retargeter)
    controller.set_ik_rig(
        unreal.RetargetSourceOrTarget.SOURCE,
        source_rig,
    )
    target_rig = controller.get_ik_rig(
        unreal.RetargetSourceOrTarget.TARGET
    )
    if target_rig is None:
        raise RuntimeError("The base Human2 retargeter has no target IK Rig")

    controller.remove_all_ops()
    controller.add_default_ops()
    controller.set_preview_mesh(
        unreal.RetargetSourceOrTarget.SOURCE,
        source_mesh,
    )
    controller.set_preview_mesh(
        unreal.RetargetSourceOrTarget.TARGET,
        target_mesh,
    )
    controller.assign_ik_rig_to_all_ops(
        unreal.RetargetSourceOrTarget.SOURCE,
        source_rig,
    )
    controller.assign_ik_rig_to_all_ops(
        unreal.RetargetSourceOrTarget.TARGET,
        target_rig,
    )
    for op_index in range(controller.get_num_retarget_ops()):
        controller.run_op_initial_setup(op_index)

    pelvis_controller = None
    op_names = []
    for op_index in range(controller.get_num_retarget_ops()):
        op_names.append(str(controller.get_op_name(op_index)))
        op_controller = controller.get_op_controller(op_index)
        if isinstance(
            op_controller,
            unreal.IKRetargetPelvisMotionController,
        ):
            pelvis_controller = op_controller
    if pelvis_controller is None:
        raise RuntimeError(f"No Pelvis Motion Op found; ops={op_names}")

    pelvis_controller.set_source_pelvis_bone("Hips")
    pelvis_controller.set_target_pelvis_bone("pelvis")
    pelvis_settings = pelvis_controller.get_settings()
    pelvis_settings.set_editor_property("translation_alpha", 1.0)
    pelvis_settings.set_editor_property("rotation_alpha", 1.0)
    pelvis_settings.set_editor_property("affect_ik_vertical", 0.0)
    pelvis_controller.set_settings(pelvis_settings)

    controller.auto_map_chains(unreal.AutoMapChainType.EXACT, True)
    controller.auto_align_all_bones(
        unreal.RetargetSourceOrTarget.SOURCE,
        unreal.RetargetAutoAlignMethod.CHAIN_TO_CHAIN,
    )
    unreal.EditorAssetLibrary.save_loaded_asset(retargeter, False)
    log(
        f"RETARGETER path={retargeter_path} ops={op_names} "
        f"source_pelvis={pelvis_controller.get_source_pelvis_bone()} "
        f"target_pelvis={pelvis_controller.get_target_pelvis_bone()}"
    )
    return retargeter


unreal.EditorAssetLibrary.make_directory(GENERATED_FOLDER)
asset_tools = unreal.AssetToolsHelpers.get_asset_tools()
target_mesh = require_asset(TARGET_MESH_PATH)
target_skeleton = target_mesh.get_editor_property("skeleton")

for variant in VARIANTS:
    source_mesh = require_asset(variant["mesh"])
    source_animation = require_asset(variant["animation"])
    source_skeleton = source_mesh.get_editor_property("skeleton")
    if source_animation.get_editor_property("skeleton") != source_skeleton:
        raise RuntimeError(
            f"{variant['name']} animation does not use its imported mesh skeleton"
        )

    source_rig = create_source_rig(
        asset_tools,
        variant["rig"],
        source_mesh,
    )
    retargeter = create_retargeter(
        variant["retargeter"],
        source_rig,
        source_mesh,
        target_mesh,
    )

    output_path = variant["output"]
    if unreal.EditorAssetLibrary.does_asset_exist(output_path):
        if not unreal.EditorAssetLibrary.delete_asset(output_path):
            raise RuntimeError(f"Could not replace {output_path}")

    results = unreal.IKRetargetBatchOperation.duplicate_and_retarget(
        [asset_data(source_animation)],
        source_mesh,
        target_mesh,
        retargeter,
        "",
        "",
        "Human2_",
        "",
        False,
        True,
    )
    if len(results) != 1:
        raise RuntimeError(
            f"Expected one {variant['name']} animation, found {results}"
        )

    generated = results[0].get_asset()
    generated_path = generated.get_path_name().split(".")[0]
    if generated_path != output_path:
        if not unreal.EditorAssetLibrary.rename_asset(
            generated_path,
            output_path,
        ):
            raise RuntimeError(
                f"Could not move {generated_path} to {output_path}"
            )

    output_animation = require_asset(output_path)
    if output_animation.get_editor_property("skeleton") != target_skeleton:
        raise RuntimeError(f"Wrong target skeleton: {output_path}")
    unreal.EditorAssetLibrary.save_loaded_asset(output_animation, False)
    log(
        f"OUTPUT variant={variant['name']} "
        f"source={source_animation.get_path_name()} "
        f"path={output_animation.get_path_name()} "
        f"length={output_animation.get_play_length():.3f} "
        f"frames={output_animation.data_model_interface.get_number_of_frames()}"
    )

log(f"SUCCESS animations={len(VARIANTS)} source=reimported_assets")
