import unreal


PREFIX = "NATURALNPC_MIXAMO_RETARGET"
SOURCE_FOLDER = "/Game/ImportedAnimations/MixamoItemActions"
SOURCE_MESH_PATH = f"{SOURCE_FOLDER}/Mixamo_PickingUp_Source"
SOURCE_PICKUP_PATH = f"{SOURCE_FOLDER}/Mixamo_PickingUp_Source_Anim"
SOURCE_BOX_WALK_PATH = f"{SOURCE_FOLDER}/A_Mixamo_BoxWalkArc"
SOURCE_RIG_PATH = f"{SOURCE_FOLDER}/IK_MixamoItemActions"
RETARGETER_PATH = f"{SOURCE_FOLDER}/RTG_Mixamo_Human2"
BASE_RETARGETER_PATH = "/Game/MetaHumans/Human2/Retarget/RTG_AutoGenerated"
TARGET_MESH_PATH = "/Game/MetaHumans/Human2/Body/SKM_Human2_BodyMesh"
OUTPUT_FOLDER = "/Game/MetaHumans/Human2/Animations/Actions"
OUTPUT_PICKUP_PATH = f"{OUTPUT_FOLDER}/Human2_PickingUp_Small"
OUTPUT_BOX_WALK_PATH = f"{OUTPUT_FOLDER}/Human2_BoxWalk_Carry"


def log(message):
    unreal.log(f"{PREFIX} {message}")


def require_asset(path):
    asset = unreal.load_asset(path)
    if asset is None:
        raise RuntimeError(f"Required asset is missing: {path}")
    return asset


def asset_data(path):
    data = unreal.EditorAssetLibrary.find_asset_data(path)
    if not data.is_valid():
        raise RuntimeError(f"Asset data is missing: {path}")
    return data


asset_tools = unreal.AssetToolsHelpers.get_asset_tools()
source_mesh = require_asset(SOURCE_MESH_PATH)
source_pickup = require_asset(SOURCE_PICKUP_PATH)
source_box_walk = require_asset(SOURCE_BOX_WALK_PATH)
target_mesh = require_asset(TARGET_MESH_PATH)

source_rig = unreal.load_asset(SOURCE_RIG_PATH)
if source_rig is None:
    source_rig = asset_tools.create_asset(
        "IK_MixamoItemActions",
        SOURCE_FOLDER,
        unreal.IKRigDefinition,
        unreal.IKRigDefinitionFactory(),
    )
if source_rig is None:
    raise RuntimeError("Could not create the Mixamo IK Rig")

rig_controller = unreal.IKRigController.get_controller(source_rig)
if not rig_controller.set_skeletal_mesh(source_mesh):
    raise RuntimeError("Could not assign the Mixamo source mesh to the IK Rig")
if not rig_controller.get_retarget_chains():
    if not rig_controller.apply_auto_generated_retarget_definition():
        raise RuntimeError("UE could not auto-generate Mixamo retarget chains")
if not rig_controller.get_retarget_root():
    raise RuntimeError("The Mixamo IK Rig has no retarget root")
unreal.EditorAssetLibrary.save_loaded_asset(source_rig, False)
log(
    f"SOURCE_RIG root={rig_controller.get_retarget_root()} "
    f"chains={rig_controller.get_retarget_chains()}"
)

retargeter = unreal.load_asset(RETARGETER_PATH)
if retargeter is None:
    retargeter = unreal.EditorAssetLibrary.duplicate_asset(
        BASE_RETARGETER_PATH,
        RETARGETER_PATH,
    )
if retargeter is None:
    raise RuntimeError("Could not create the Mixamo to Human2 retargeter")

retarget_controller = unreal.IKRetargeterController.get_controller(retargeter)
retarget_controller.set_ik_rig(
    unreal.RetargetSourceOrTarget.SOURCE,
    source_rig,
)
retarget_controller.auto_map_chains(
    unreal.AutoMapChainType.EXACT,
    True,
)
retarget_controller.auto_align_all_bones(
    unreal.RetargetSourceOrTarget.SOURCE,
    unreal.RetargetAutoAlignMethod.CHAIN_TO_CHAIN,
)
unreal.EditorAssetLibrary.save_loaded_asset(retargeter, False)
log(
    f"RETARGETER source={retarget_controller.get_ik_rig(unreal.RetargetSourceOrTarget.SOURCE)} "
    f"target={retarget_controller.get_ik_rig(unreal.RetargetSourceOrTarget.TARGET)}"
)

for output_path in (OUTPUT_PICKUP_PATH, OUTPUT_BOX_WALK_PATH):
    if unreal.EditorAssetLibrary.does_asset_exist(output_path):
        if not unreal.EditorAssetLibrary.delete_asset(output_path):
            raise RuntimeError(f"Could not replace {output_path}")

results = unreal.IKRetargetBatchOperation.duplicate_and_retarget(
    [asset_data(SOURCE_PICKUP_PATH), asset_data(SOURCE_BOX_WALK_PATH)],
    source_mesh,
    target_mesh,
    retargeter,
    "",
    "",
    "Human2_",
    "",
    False,
    True,
)
if len(results) != 2:
    raise RuntimeError(f"Expected two retargeted animations, found {results}")

generated_assets = [result.get_asset() for result in results]
desired_paths = (OUTPUT_PICKUP_PATH, OUTPUT_BOX_WALK_PATH)
for generated, desired_path in zip(generated_assets, desired_paths):
    generated_path = generated.get_path_name().split(".")[0]
    if generated_path != desired_path:
        if not unreal.EditorAssetLibrary.rename_asset(generated_path, desired_path):
            raise RuntimeError(
                f"Could not move {generated_path} to {desired_path}"
            )

target_skeleton = target_mesh.get_editor_property("skeleton")
for path in desired_paths:
    animation = require_asset(path)
    if animation.get_editor_property("skeleton") != target_skeleton:
        raise RuntimeError(f"Retargeted animation has the wrong skeleton: {path}")
    unreal.EditorAssetLibrary.save_loaded_asset(animation, False)
    log(
        f"ANIMATION path={animation.get_path_name()} "
        f"length={animation.get_play_length():.3f} "
        f"frames={animation.data_model_interface.get_number_of_frames()}"
    )

log("SUCCESS animations=2")
